console.log("Fetch employees data from a rest dummy API")
// const emps = fetch("http://dummy.restapiexample.com/api/v1/employees")
// console.log('Done Fetching')
// console.log(emps)
fetch("http://dummy.restapiexample.com/api/v1/employees")
    .then(data => data.json())
    // .then(employees => console.log(employees))
    .catch(err => {
        console.error(err)
    })